services:
  - type: web
    name: marketscope-backend
    env: python
    rootDir: marketscope-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: MARKETSCOPE_HOST
        value: 0.0.0.0
      - key: PORT
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSLMODE
        value: require