"""MSME business categories, their scoring profiles, and OSM matching tables."""


VERIFIED_LOCAL_FEATURE_KINDS = {"msme", "anchor", "road", "building"}


SME_DATABASE = {
    "coffee": {"key": "amenity", "val": "cafe", "fear": 6, "need": 9, "name": "Coffee Shops", "osm_tags": [("amenity", "cafe"), ("shop", "coffee")]},
    "print": {"key": "shop", "val": "copyshop", "fear": 7, "need": 6, "name": "Print/Copy Centers", "osm_tags": [("shop", "copyshop"), ("shop", "stationery"), ("shop", "books")]},
    "laundry": {"key": "shop", "val": "laundry", "fear": 9, "need": 7, "name": "Laundry Shops", "osm_tags": [("shop", "laundry"), ("shop", "dry_cleaning")]},
    "carwash": {"key": "amenity", "val": "car_wash", "fear": 8, "need": 9, "name": "Car Washes", "osm_tags": [("amenity", "car_wash"), ("shop", "car_repair")]},
    "kiosk": {"key": "amenity", "val": "fast_food", "fear": 6, "need": 9, "name": "Food Kiosks/Stalls", "osm_tags": [("amenity", "fast_food"), ("amenity", "food_court"), ("shop", "kiosk")]},
    "water": {"key": "shop", "val": "water", "fear": 4, "need": 7, "name": "Water Refilling Stations", "osm_tags": [("shop", "water"), ("amenity", "drinking_water"), ("amenity", "water_point")]},
    "bakery": {"key": "shop", "val": "bakery", "fear": 8, "need": 9, "name": "Bakeries", "osm_tags": [("shop", "bakery"), ("shop", "pastry")]},
    "pharmacy": {"key": "amenity", "val": "pharmacy", "fear": 7, "need": 9, "name": "Small Pharmacies", "osm_tags": [("amenity", "pharmacy"), ("shop", "chemist")]},
    "barber": {"key": "shop", "val": "hairdresser", "fear": 7, "need": 9, "name": "Barbershops/Salons", "osm_tags": [("shop", "hairdresser"), ("shop", "beauty")]},
    "moto": {"key": "shop", "val": "motorcycle_repair", "fear": 5, "need": 8, "name": "Motorcycle Repair Shops", "osm_tags": [("shop", "motorcycle"), ("shop", "motorcycle_repair"), ("shop", "car_repair")]},
    "internet": {"key": "amenity", "val": "internet_cafe", "fear": 6, "need": 6, "name": "Internet Cafes", "osm_tags": [("amenity", "internet_cafe"), ("amenity", "cafe")]},
    "meat": {"key": "shop", "val": "butcher", "fear": 9, "need": 9, "name": "Meat Shops", "osm_tags": [("shop", "butcher"), ("shop", "deli")]},
    "hardware": {"key": "shop", "val": "hardware", "fear": 7, "need": 8, "name": "Hardware/Construction Supplies", "osm_tags": [("shop", "hardware"), ("shop", "doityourself"), ("shop", "trade")]}
}


MSME_CATEGORY_PROFILES = {
    "coffee": {
        "display_name": "Coffee Shops",
        "osm_tags": [("amenity", "cafe"), ("shop", "coffee")],
        "competition_sensitivity": 1.38,
        "competition_weight": 0.47,
        "road_weight": 0.20,
        "anchor_weight": 0.19,
        "building_weight": 0.14,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 700.0,
        "anchor_scale_m": 300.0,
        "anchor_target_power": 40.0,
        "building_radius_scale_m": 360.0,
    },
    "print": {
        "display_name": "Print/Copy Centers",
        "osm_tags": [("shop", "copyshop"), ("shop", "stationery"), ("shop", "books")],
        "competition_sensitivity": 1.12,
        "competition_weight": 0.42,
        "road_weight": 0.23,
        "anchor_weight": 0.18,
        "building_weight": 0.17,
        "preferred_road_classes": ["tertiary", "secondary", "primary"],
        "required_road_classes": ["tertiary", "secondary", "primary"],
        "road_distance_soft_cap_m": 820.0,
        "anchor_scale_m": 340.0,
        "anchor_target_power": 34.0,
        "building_radius_scale_m": 420.0,
    },
    "laundry": {
        "display_name": "Laundry Shops",
        "osm_tags": [("shop", "laundry"), ("shop", "dry_cleaning")],
        "competition_sensitivity": 1.18,
        "competition_weight": 0.43,
        "road_weight": 0.20,
        "anchor_weight": 0.19,
        "building_weight": 0.18,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 780.0,
        "anchor_scale_m": 320.0,
        "anchor_target_power": 36.0,
        "building_radius_scale_m": 420.0,
    },
    "carwash": {
        "display_name": "Car Washes",
        "osm_tags": [("amenity", "car_wash"), ("shop", "car_repair")],
        "competition_sensitivity": 1.10,
        "competition_weight": 0.39,
        "road_weight": 0.28,
        "anchor_weight": 0.16,
        "building_weight": 0.17,
        "preferred_road_classes": ["trunk", "primary", "secondary"],
        "required_road_classes": ["trunk", "primary", "secondary"],
        "road_distance_soft_cap_m": 920.0,
        "anchor_scale_m": 360.0,
        "anchor_target_power": 38.0,
        "building_radius_scale_m": 450.0,
    },
    "kiosk": {
        "display_name": "Food Kiosks/Stalls",
        "osm_tags": [("amenity", "fast_food"), ("amenity", "food_court"), ("shop", "kiosk")],
        "competition_sensitivity": 1.34,
        "competition_weight": 0.44,
        "road_weight": 0.18,
        "anchor_weight": 0.22,
        "building_weight": 0.16,
        "preferred_road_classes": ["primary", "secondary", "tertiary"],
        "required_road_classes": ["primary", "secondary", "tertiary"],
        "road_distance_soft_cap_m": 650.0,
        "anchor_scale_m": 280.0,
        "anchor_target_power": 42.0,
        "building_radius_scale_m": 340.0,
    },
    "water": {
        "display_name": "Water Refilling Stations",
        "osm_tags": [("shop", "water"), ("amenity", "drinking_water"), ("amenity", "water_point")],
        "competition_sensitivity": 0.98,
        "competition_weight": 0.36,
        "road_weight": 0.22,
        "anchor_weight": 0.18,
        "building_weight": 0.24,
        "preferred_road_classes": ["residential", "service", "tertiary", "secondary"],
        "required_road_classes": ["residential", "service", "tertiary", "secondary"],
        "road_distance_soft_cap_m": 860.0,
        "anchor_scale_m": 360.0,
        "anchor_target_power": 30.0,
        "building_radius_scale_m": 460.0,
    },
    "bakery": {
        "display_name": "Bakeries",
        "osm_tags": [("shop", "bakery"), ("shop", "pastry")],
        "competition_sensitivity": 1.28,
        "competition_weight": 0.44,
        "road_weight": 0.20,
        "anchor_weight": 0.19,
        "building_weight": 0.17,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 760.0,
        "anchor_scale_m": 320.0,
        "anchor_target_power": 38.0,
        "building_radius_scale_m": 380.0,
    },
    "pharmacy": {
        "display_name": "Small Pharmacies",
        "osm_tags": [("amenity", "pharmacy"), ("shop", "chemist")],
        "competition_sensitivity": 1.22,
        "competition_weight": 0.43,
        "road_weight": 0.21,
        "anchor_weight": 0.22,
        "building_weight": 0.14,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 720.0,
        "anchor_scale_m": 300.0,
        "anchor_target_power": 40.0,
        "building_radius_scale_m": 340.0,
    },
    "barber": {
        "display_name": "Barbershops/Salons",
        "osm_tags": [("shop", "hairdresser"), ("shop", "beauty")],
        "competition_sensitivity": 1.24,
        "competition_weight": 0.45,
        "road_weight": 0.19,
        "anchor_weight": 0.20,
        "building_weight": 0.16,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 760.0,
        "anchor_scale_m": 320.0,
        "anchor_target_power": 39.0,
        "building_radius_scale_m": 360.0,
    },
    "moto": {
        "display_name": "Motorcycle Repair Shops",
        "osm_tags": [("shop", "motorcycle"), ("shop", "motorcycle_repair"), ("shop", "car_repair")],
        "competition_sensitivity": 1.06,
        "competition_weight": 0.40,
        "road_weight": 0.30,
        "anchor_weight": 0.14,
        "building_weight": 0.16,
        "preferred_road_classes": ["trunk", "primary", "secondary"],
        "required_road_classes": ["trunk", "primary", "secondary"],
        "road_distance_soft_cap_m": 980.0,
        "anchor_scale_m": 380.0,
        "anchor_target_power": 32.0,
        "building_radius_scale_m": 430.0,
    },
    "internet": {
        "display_name": "Internet Cafes",
        "osm_tags": [("amenity", "internet_cafe"), ("amenity", "cafe")],
        "competition_sensitivity": 1.15,
        "competition_weight": 0.41,
        "road_weight": 0.21,
        "anchor_weight": 0.20,
        "building_weight": 0.18,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 760.0,
        "anchor_scale_m": 330.0,
        "anchor_target_power": 34.0,
        "building_radius_scale_m": 400.0,
    },
    "meat": {
        "display_name": "Meat Shops",
        "osm_tags": [("shop", "butcher"), ("shop", "deli")],
        "competition_sensitivity": 1.20,
        "competition_weight": 0.42,
        "road_weight": 0.20,
        "anchor_weight": 0.20,
        "building_weight": 0.18,
        "preferred_road_classes": ["secondary", "tertiary", "primary"],
        "required_road_classes": ["secondary", "tertiary", "primary"],
        "road_distance_soft_cap_m": 740.0,
        "anchor_scale_m": 300.0,
        "anchor_target_power": 35.0,
        "building_radius_scale_m": 360.0,
    },
    "hardware": {
        "display_name": "Hardware/Construction Supplies",
        "osm_tags": [("shop", "hardware"), ("shop", "doityourself"), ("shop", "trade")],
        "competition_sensitivity": 1.04,
        "competition_weight": 0.40,
        "road_weight": 0.30,
        "anchor_weight": 0.14,
        "building_weight": 0.16,
        "preferred_road_classes": ["trunk", "primary", "secondary"],
        "required_road_classes": ["trunk", "primary", "secondary"],
        "road_distance_soft_cap_m": 1000.0,
        "anchor_scale_m": 420.0,
        "anchor_target_power": 30.0,
        "building_radius_scale_m": 460.0,
    },
}


SME_PROFILE_BY_NAME = {
    str(profile.get("name") or "").strip().lower(): key
    for key, profile in SME_DATABASE.items()
    if str(profile.get("name") or "").strip()
}


PBF_NAME_KEYWORD_FALLBACK = {
    "coffee": ["coffee", "cafe"],
    "print": ["print", "copy", "xerox"],
    "laundry": ["laundry", "wash", "dry clean"],
    "carwash": ["car wash", "autowash", "auto spa"],
    "kiosk": ["kiosk", "snack", "food"],
    "water": ["water refilling", "water station", "purified water"],
    "bakery": ["bakery", "bakeshop", "bread"],
    "pharmacy": ["pharmacy", "drugstore", "mercury"],
    "barber": ["barber", "salon", "hair"],
    "moto": ["motor", "motorcycle", "moto", "repair"],
    "internet": ["internet", "computer", "cyber"],
    "meat": ["meat", "butcher"],
    "hardware": ["hardware", "construction", "tools"],
}


COMMERCIAL_AMENITY_VALUES = {
    "cafe", "restaurant", "fast_food", "food_court", "pharmacy", "bank", "fuel", "marketplace",
    "car_wash", "clinic", "hospital", "internet_cafe", "bar", "pub", "biergarten"
}


ROAD_CLASS_BASE_SCORES = {
    "motorway": 25,
    "trunk": 24,
    "primary": 23,
    "secondary": 21,
    "tertiary": 18,
    "unclassified": 15,
    "living_street": 13,
    "residential": 11,
    "service": 8,
    "track": 6,
    "path": 4,
    "footway": 3,
    "cycleway": 4,
    "pedestrian": 5,
}


DEFAULT_MSME_ANALYSIS_PROFILE = {
    "display_name": "MSME",
    "osm_tags": [("shop", "convenience")],
    "competition_sensitivity": 1.0,
    "competition_weight": 0.42,
    "road_weight": 0.23,
    "anchor_weight": 0.20,
    "building_weight": 0.15,
    "preferred_road_classes": ["primary", "secondary", "tertiary"],
    "required_road_classes": ["primary", "secondary", "tertiary"],
    "road_distance_soft_cap_m": 850.0,
    "anchor_scale_m": 320.0,
    "anchor_target_power": 36.0,
    "building_radius_scale_m": 420.0,
}
